@token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MDQ3NzYzOTQuMTExLCJuYmYiOjE2MDQ3NzYzOTQuMTExLCJleHAiOjE2MDk5NjAzOTQuMTExLCJqdGkiOjE2MDQ3NzYzOTQuMTExLCJhcHBsaWNhdGlvbl9pZCI6IjlkZjUwMmQ5LTc4NGUtNGYzZi04YjIzLWU4ZmFmNDM4ZWI4ZiIsImFjbCI6eyJwYXRocyI6eyIvKioiOnt9fX19.tm8pHPR5EUIT7-pZsfnC7GENVij51vaxjRvdUUkYt9OyV1QUfiy9YLjmRrJId5uAyUupvxsGLkdSeGg_Ah0IpsAqPiF8yUuPFv_GRkKr3MfDvQJ9kjdwYJ1k4J3nyRjsLCKCzZ2AqhPYGlakmwr2K3cGNZ4wzFF56m2O9nuT2VWgDiNlkfZOnHY2Njcs9u3aa9QoA_YqelQi8wrASMh-gZksNa9pYsetrFqmdKfcBPRJoqrmXEN-2-_cbV6GG61YFk1WKgS-85np16e8qP9cEWN75f5I6muEvjY4p_IKviC9brr9X9IdVw06T64eZZ0bI5r85QT6f3oxwHEJgcj0SQ

###
GET https://api.nexmo.com/v0.3/users
content-type: application/json
Authorization: Bearer {{token}}