@token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MDUyNjcyNzMuMzU1LCJuYmYiOjE2MDUyNjcyNzMuMzU1LCJleHAiOjE2MTA0NTEyNzMuMzU1LCJqdGkiOjE2MDUyNjcyNzMuMzU1LCJhcHBsaWNhdGlvbl9pZCI6IjlkZjUwMmQ5LTc4NGUtNGYzZi04YjIzLWU4ZmFmNDM4ZWI4ZiIsImFjbCI6eyJwYXRocyI6eyIvKioiOnt9fX19.PV2l8mrExo7MqkmfAdlrPmsPNZ5k5cX0D9uMclO15g2DcYk7lfqRX_EWJn04Dn1kH_BqXK1Lg_uZesWyS2SgUgXDIHiMYuzcT1RWGgAk-A1K_uVsE57wF_gAUzimUq19wTfJmnKRpbJ8gVnSxbYuW50ZV3-3hlxTbJFZ9Wu6TNEc2rrPCNxGDNSEfhXp4ab7Sb48gyCZaDKnlw1xLwkWie4XKtSRc-omUefjSZYpnAB-AxfneXZekFd_6src1-UKUS_yevuk56yh5ENPvNgfZZp0F2lfyqAjJu49TbhWF-fhJKlc20nG5sSywaYquV-JpiImcvFePpufhimaAzNtuA
@token_user=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MDUxMTczMzAuMDM3LCJuYmYiOjE2MDUxMTczMzAuMDM3LCJleHAiOjE2MTAzMDEzMzAuMDM3LCJqdGkiOjE2MDUxMTczMzAuMDM3LCJhcHBsaWNhdGlvbl9pZCI6IjlkZjUwMmQ5LTc4NGUtNGYzZi04YjIzLWU4ZmFmNDM4ZWI4ZiIsImFjbCI6eyJwYXRocyI6eyIvKioiOnt9fX0sInN1YiI6Imp1cmdvIn0.PzzlYfXzEHvgsRMx4Lj5t2Vq1n9SZLcIhr6vrMZZb-eGCNvSxdHRLO-zHuU7S9yLrBaYQjiS8ife2BuW0kATXpHLNELUvc-NcwgsVpuwl8x7UnnbRTSXkdNhC8NnHE0mQtxynYfU7tBsyUHaEz28z79PHtxptpNtmcvmFF7Vww_9VSM-LmZa49sOWP0ac06BPZ0kMlLexhKLS1oBq3OyhUklhOc9AJe6jQxVOTVlKlAsiM6XiZXGQQD9ElVXoSN0uukOtAtkLhalgENntEou0O7-u0HyqPHy-kxjy3Xm60Q4QoMWBnYFcM3KEyhV46TXGr5_sNQmw1a5DaTsjwifXg"

@datacenter=https://api-eu-1.nexmo.com
#@datacenter=https://api.nexmo.com

###
GET {{datacenter}}/v0.3/users
content-type: application/json
Authorization: Bearer {{token}}

### 

GET {{datacenter}}/v0.3/users/USR-ec219045-4ff3-4081-9c8c-8c661d16ec45
content-type: application/json
Authorization: Bearer {{token}}

###

GET {{datacenter}}/v0.3/users/USR-a2157ff4-13a4-4ca8-892c-504fa11409e7/conversations
content-type: application/json
Authorization: Bearer {{token_user}}
