

### 
POST http://localhost:5001/login
content-type: application/json

{
    "user":"jurgo"
}

### register a new user
POST http://localhost:5001/subscribe
content-type: application/json

{
    "username":"jurgo2"
}


### get user
GET  http://localhost:5001/users
content-type: application/json

### delete all users
DELETE  http://localhost:5001/users
content-type: application/json

